security:
  providers:
    our_db_provider:
      entity:
        class: App\Entity\User\User
        property: email

  encoders:
    App\Entity\User\User:
        algorithm: bcrypt

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      provider: our_db_provider
      pattern:    ^/
      anonymous: ~

      form_login:
        login_path: app_site_user_login_login
        check_path: app_site_user_login_login
      logout:
        path:   /logout
        target: /

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER

  access_control:
      - { path: ^/admin, roles: ROLE_ADMIN }
      - { path: ^/user, roles: ROLE_USER }
      - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }